CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory"
(
    "MigrationId"    character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Billboards"
(
    "BillboardId"         integer GENERATED BY DEFAULT AS IDENTITY,
    "RegistrationNumber"  text    NOT NULL,
    "CityDistrict"        text    NOT NULL,
    "Address"             text    NOT NULL,
    "LocationDescription" text,
    "UsefulArea"          numeric NOT NULL,
    CONSTRAINT "PK_Billboards" PRIMARY KEY ("BillboardId")
);

CREATE TABLE "Renters"
(
    "RenterId"           integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"               text NOT NULL,
    "Status"             text NOT NULL,
    "LegalAddress"       text NOT NULL,
    "DirectorName"       text NOT NULL,
    "DirectorPhone"      text NOT NULL,
    "ContactPersonName"  text NOT NULL,
    "ContactPersonPhone" text NOT NULL,
    "BankName"           text NOT NULL,
    "BankAccountNumber"  text NOT NULL,
    "Inn"                text NOT NULL,
    CONSTRAINT "PK_Renters" PRIMARY KEY ("RenterId")
);

CREATE TABLE "Contracts"
(
    "ContractId"        integer GENERATED BY DEFAULT AS IDENTITY,
    "ContractNumber"    text                     NOT NULL,
    "SigningDate"       timestamp with time zone NOT NULL,
    "AgencyResponsible" text                     NOT NULL,
    "TotalAmount"       numeric                  NOT NULL,
    "PaymentType"       text                     NOT NULL,
    "AdditionalTerms"   text                     NOT NULL,
    "RenterId"          integer                  NOT NULL,
    CONSTRAINT "PK_Contracts" PRIMARY KEY ("ContractId"),
    CONSTRAINT "FK_Contracts_Renters_RenterId" FOREIGN KEY ("RenterId") REFERENCES "Renters" ("RenterId") ON DELETE CASCADE
);

CREATE TABLE "Users"
(
    "UserId"       integer GENERATED BY DEFAULT AS IDENTITY,
    "Username"     text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role"         text NOT NULL,
    "RenterId"     integer,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_Users_Renters_RenterId" FOREIGN KEY ("RenterId") REFERENCES "Renters" ("RenterId")
);

CREATE TABLE "AdvertisementWorks"
(
    "WorkId"          integer GENERATED BY DEFAULT AS IDENTITY,
    "ContractId"      integer NOT NULL,
    "WorkDescription" text,
    "WorkCost"        numeric NOT NULL,
    CONSTRAINT "PK_AdvertisementWorks" PRIMARY KEY ("WorkId"),
    CONSTRAINT "FK_AdvertisementWorks_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("ContractId") ON DELETE CASCADE
);

CREATE TABLE "ContractBillboards"
(
    "Id"                 integer GENERATED BY DEFAULT AS IDENTITY,
    "ContractId"         integer                  NOT NULL,
    "BillboardId"        integer                  NOT NULL,
    "RentStartDate"      timestamp with time zone NOT NULL,
    "RentEndDate"        timestamp with time zone NOT NULL,
    "RentAmount"         numeric                  NOT NULL,
    "AdvertisementPhoto" bytea                    NOT NULL,
    CONSTRAINT "PK_ContractBillboards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContractBillboards_Billboards_BillboardId" FOREIGN KEY ("BillboardId") REFERENCES "Billboards" ("BillboardId") ON DELETE CASCADE,
    CONSTRAINT "FK_ContractBillboards_Contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES "Contracts" ("ContractId") ON DELETE CASCADE
);

CREATE TABLE "AuditLogs"
(
    "LogId"           integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"          integer                  NOT NULL,
    "Action"          text                     NOT NULL,
    "TableName"       text                     NOT NULL,
    "RecordId"        integer,
    "ActionTimestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("LogId"),
    CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_AdvertisementWorks_ContractId" ON "AdvertisementWorks" ("ContractId");

CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");

CREATE INDEX "IX_ContractBillboards_BillboardId" ON "ContractBillboards" ("BillboardId");

CREATE INDEX "IX_ContractBillboards_ContractId" ON "ContractBillboards" ("ContractId");

CREATE INDEX "IX_Contracts_RenterId" ON "Contracts" ("RenterId");

CREATE INDEX "IX_Users_RenterId" ON "Users" ("RenterId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240820112557_Initial', '9.0.0-preview.3.24172.4');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240820131515_Update', '9.0.0-preview.3.24172.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "AuditLogs"
    DROP COLUMN "ActionTimestamp";

ALTER TABLE "Users"
    ALTER COLUMN "Username" DROP NOT NULL;

ALTER TABLE "Users"
    ALTER COLUMN "PasswordHash" DROP NOT NULL;

ALTER TABLE "Renters"
    ALTER COLUMN "Name" DROP NOT NULL;

ALTER TABLE "AuditLogs"
    ADD "Version" bytea NOT NULL DEFAULT BYTEA E'\\x';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240823114734_update_timestamp', '9.0.0-preview.3.24172.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "Contracts"
    ALTER COLUMN "SigningDate" TYPE bytea;
ALTER TABLE "Contracts"
    ALTER COLUMN "SigningDate" DROP NOT NULL;

ALTER TABLE "Contracts"
    ALTER COLUMN "PaymentType" DROP NOT NULL;

ALTER TABLE "Contracts"
    ALTER COLUMN "ContractNumber" DROP NOT NULL;

ALTER TABLE "Contracts"
    ALTER COLUMN "AgencyResponsible" DROP NOT NULL;

ALTER TABLE "Contracts"
    ALTER COLUMN "AdditionalTerms" DROP NOT NULL;

ALTER TABLE "ContractBillboards"
    ALTER COLUMN "RentStartDate" TYPE bytea;
ALTER TABLE "ContractBillboards"
    ALTER COLUMN "RentStartDate" DROP NOT NULL;

ALTER TABLE "ContractBillboards"
    ALTER COLUMN "RentEndDate" TYPE bytea;
ALTER TABLE "ContractBillboards"
    ALTER COLUMN "RentEndDate" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240823142301_update_timestamps', '9.0.0-preview.3.24172.4');

COMMIT;

START TRANSACTION;

UPDATE "Contracts"
SET "SigningDate" = BYTEA E'\\x'
WHERE "SigningDate" IS NULL;
ALTER TABLE "Contracts"
    ALTER COLUMN "SigningDate" SET NOT NULL;
ALTER TABLE "Contracts"
    ALTER COLUMN "SigningDate" SET DEFAULT BYTEA E'\\x';

UPDATE "ContractBillboards"
SET "RentStartDate" = BYTEA E'\\x'
WHERE "RentStartDate" IS NULL;
ALTER TABLE "ContractBillboards"
    ALTER COLUMN "RentStartDate" SET NOT NULL;
ALTER TABLE "ContractBillboards"
    ALTER COLUMN "RentStartDate" SET DEFAULT BYTEA E'\\x';

UPDATE "ContractBillboards"
SET "RentEndDate" = BYTEA E'\\x'
WHERE "RentEndDate" IS NULL;
ALTER TABLE "ContractBillboards"
    ALTER COLUMN "RentEndDate" SET NOT NULL;
ALTER TABLE "ContractBillboards"
    ALTER COLUMN "RentEndDate" SET DEFAULT BYTEA E'\\x';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240823142538_update-t', '9.0.0-preview.3.24172.4');

COMMIT;

